apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.5.15
        command:
          - /usr/local/bin/etcd
          - --name=s1
          - --data-dir=/etcd-data
          - --listen-client-urls=http://0.0.0.0:2379
          - --advertise-client-urls=http://192.168.49.2:2379
          - --listen-peer-urls=http://0.0.0.0:2380
          - --initial-advertise-peer-urls=http://192.168.49.2:2380
          - --initial-cluster=s1=http://192.168.49.2:2380
          - --initial-cluster-token=tkn
          - --initial-cluster-state=new
          - --log-level=info
          - --logger=zap
          - --log-outputs=stderr
        ports:
        - containerPort: 2379
          name: client-port
        - containerPort: 2380
          name: peer-port
        volumeMounts:
        - mountPath: /etcd-data
          name: etcd-data
      volumes:
      - name: etcd-data
        emptyDir: {}
