apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-scale-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-scale-role
rules:
- apiGroups: ["", "apps", "autoscaling"]
  resources: ["pods", "services", "deployments", "replicasets", "horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-scale-rolebinding
subjects:
- kind: ServiceAccount
  name: monitor-scale-sa
roleRef:
  kind: Role
  name: monitor-scale-role
  apiGroup: rbac.authorization.k8s.io
