node {
    checkout scm
    env.DOCKER_API_VERSION="1.46"
    sh "git rev-parse --short HEAD > commit-id"
    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "puzzle"
    registryHost = "192.168.49.2:30400/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName
    env.BUILD_TAG=tag
    
    stage("Build") {
        sh "docker build -t ${imageName} applications/puzzle"
    }
    
    stage("Push") {
        sh "docker push ${imageName}"
    }
    
    stage("Deploy") {
        sh "envsubst < applications/${appName}/k8s/deployment.yaml > temp_deployment.yaml"
        sh "kubectl apply -f temp_deployment.yaml"
        sh "kubectl apply -f applications/${appName}/k8s/service.yaml"
        sh "kubectl apply -f applications/${appName}/k8s/ingress.yaml"
        sh "rm temp_deployment.yaml"
    }
}
