node {

    checkout scm

    env.DOCKER_API_VERSION="1.46"

    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').trim()
    appName = "puzzle"
    registryHost = "192.168.49.2:30400/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName
    env.BUILD_TAG=tag

    stage("Build") {
        sh "docker build -t ${imageName} applications/puzzle"
    }
    stage("Push") {
        sh "docker push ${imageName}"
    }
    stage("Deploy") {
        sh """
            sed 's#192.168.49.2:30400/puzzle:\$BUILD_TAG#${imageName}#' applications/puzzle/k8s/deployment.yaml | kubectl apply -f -
        """
    }
}
