kind: Service
apiVersion: v1
metadata:
  name: example-etcd-cluster-client-service
spec:
  selector:
    app: etcd
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379
    nodePort: 32379
  type: ClusterIP
