apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: default
spec:
  selector:
    app: etcd  
  ports:
  - protocol: TCP
    port: 2379       
    targetPort: 2379
    # nodePort: 32379
  type: NodePort 
