apiVersion: v1
kind: Service
metadata:
  name: example-etcd-cluster-client-service
spec:
  selector:
    app: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
  type: ClusterIP
