apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: test
  namespace: default
spec:
  size: 3
  version: "v3.5.12"
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
    volumeClaimTemplates:
      - metadata:
          name: etcd-data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: "1Gi"
