apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-scale
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: monitor-scale-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["deployments/scale"]
  verbs: ["update", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-scale-role-binding
  namespace: default
roleRef:
  kind: Role
  name: monitor-scale-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: monitor-scale
  namespace: default
