node {

    checkout scm

    env.DOCKER_API_VERSION="1.46"
    
    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "monitor-scale"
    registryHost = "192.168.49.2:30400/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName
    env.BUILD_TAG=tag

    stage("Build") {
        sh "docker build -t ${imageName} applications/monitor-scale"
    }
    
    stage("Push") {
        sh "docker push ${imageName}"
    }

    stage("Deploy") {
        // Sử dụng kubectl apply để deploy thay vì kubernetesDeploy
        sh "kubectl apply -f applications/${appName}/k8s/"
    }
}
